# Generated by Django 4.2.7 on 2023-12-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_relation_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
