# Generated by Django 4.2.7 on 2023-12-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_relation_extraction', '0002_alter_project_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='doccano_task_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
